function [fitresult, gof] = fit_distance_to_heatflux(heat_flux_batch1D, R_1D,plt)
%CREATEFIT(HEAT_FLUX_BATCH1D,R_1D)
%  Create a fit :  distance = f ( heat flux )
%
%  Data for 'untitled fit 1' fit:
%      X Input : heat_flux_batch1D
%      Y Output: R_1D
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Sep-2019 15:18:06


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( heat_flux_batch1D, R_1D );

% Set up fittype and options.
ft = fittype( 'power2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'off';
%opts.StartPoint = [142.434424151289 -0.365175200128658 6.82568565566695];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

%Plot fit with data.
if (plt == 1)
    
    figure( 'Name', 'Curve fitting of distance = f (heatflux)' );
    h = plot( fitresult, xData, yData );
    legend( h, 'distance vs. heatflux', 'fit  : Distance = F(heat flux) ', 'Location', 'NorthEast' );
    title('Curve fitting of distance = f (heatflux) ') ;

    xlabel('heatflux [kw/m2]');
    ylabel('distance [m]');
    grid on

    dim = [0.2 0.5 0.3 0.3];
    str =  {formula(fitresult),coeffvalues(fitresult),'R^2 = ',gof.rsquare};
    annotation('textbox',dim,'String',str,'FitBoxToText','on');
end


end
 
