function [fitresult, gof] = fit_get_distance(heat_flux_batch1D, R_1D)
%CREATEFIT(HEAT_FLUX_BATCH1D,R_1D)
%  Create a fit.
%
%  Data for 'fit_get_distance' fit:
%      X Input : heat_flux_batch1D
%      Y Output: R_1D
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Sep-2019 21:51:28


%% Fit: 'fit_get_distance'.
[xData, yData] = prepareCurveData( heat_flux_batch1D, R_1D );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
%opts.StartPoint = [149.850265848751 -0.210911617266792 -9.43624318593989 -0.406467365034028];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'fit_get_distance' );
% h = plot( fitresult, xData, yData );
% legend( h, 'R_1D vs. heat_flux_batch1D', 'fit_get_distance', 'Location', 'NorthEast' );
% % Label axes
% xlabel heat_flux_batch1D
% ylabel R_1D
% grid on


