function [fitresult, gof] = fit_get_heatflux(R_1D, heat_flux_batch1D)
%CREATEFIT(R_1D,HEAT_FLUX_BATCH1D)
%  Create a fit.
%
%  Data for 'fit_get_heatflux' fit:
%      X Input : R_1D
%      Y Output: heat_flux_batch1D
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Sep-2019 21:46:42


%% Fit: 'fit_get_heatflux'.
[xData, yData] = prepareCurveData( R_1D, heat_flux_batch1D );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
%%opts.StartPoint = [-892.936055232887 -0.0370405370305288 946.087946647427 -0.0380438480963971];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
% 
% % Plot fit with data.
% figure( 'Name', 'fit_get_heatflux' );
% h = plot( fitresult, xData, yData );
% legend( h, 'heat_flux_batch1D vs. R_1D', 'fit_get_heatflux', 'Location', 'NorthEast' );
% % Label axes
% xlabel R_1D
% ylabel heat_flux_batch1D
% grid on
% 
% 
