function [fitresult, gof] = fit_get_heatflux(R_1D, heat_flux_batch1D)
%CREATEFIT(R_1D,HEAT_FLUX_BATCH1D)
%  Create a fit.
%
%  Data for 'heatflux_f_R1D' fit:
%      X Input : R_1D
%      Y Output: heat_flux_batch1D
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Sep-2019 20:06:21


%% Fit: 'heatflux_f_R1D'.
[xData, yData] = prepareCurveData( R_1D, heat_flux_batch1D );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
% opts.StartPoint = [85.7129978864077 -0.0052584677036052];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'heatflux_f_R1D' );
% h = plot( fitresult, xData, yData );
% legend( h, 'heat_flux_batch1D vs. R_1D', 'heatflux_f_R1D', 'Location', 'NorthEast' );
% % Label axes
% xlabel R_1D
% ylabel heat_flux_batch1D
% grid on


